import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from sklearn.linear_model import LinearRegression


x = np.array([[3], [7], [6], [5], [1], [2], [9], [16]])
y = np.array([1, 3, 5, 7, 9, 11, 13, 15])
plt.scatter(x, y, marker='x', c='r')
plt.title("NESA Course Specifications Data")
plt.ylabel('Training targets')
plt.xlabel('Training features')
plt.show()
m = len(x)
print(f"Number of training examples is: {m}")
my_model = LinearRegression()
my_model.fit(x, y)
y_pred = my_model.predict(x)
plt.plot(x, y_pred)
plt.scatter(x, y, marker='x', c='b', zorder=2)
plt.title("Linear Regresion Model")
plt.ylabel('Training targets')
plt.xlabel('Training features')
plt.xlim(left=-1)
plt.ylim(bottom=-1)
plt.show()
test = np.array([4.5])
predict = np.array([4.5]).reshape(1, -1)
y_prediction = my_model.predict(predict)
y_pred = my_model.predict(x)
plt.plot(x, y_pred)
plt.scatter(x, y, marker='x', c='r')
plt.scatter(predict, y_prediction, marker='D', c='r', zorder=10, s=100)
plt.title("NESA Course Specifications Data")
plt.ylabel('Example targets')
plt.xlabel('Example features')
plt.show()
print(f"predicted feature is: {y_prediction}")
# predicted feature is: [7.14141414]
# analyses and makes a prediction based on data